import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import {
  BannerInterface,
  BlogInterface,
  ProductInterface,
} from "../interface/Interface";
interface Props {
  allBlogs: BlogInterface[];
  allProducts: ProductInterface[];
  banner: BannerInterface;
}
const Home: NextPage<Props> = ({ allBlogs, allProducts, banner }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner banner={banner} />
      <CategoryPicker />
      <FeaturedProducts allProducts={allProducts} />
      <FeaturedBlogs allBlogs={allBlogs} />
    </>
  );
};
export const getStaticProps: GetStaticProps = async () => {
  const allProductsRes = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const allProducts: ProductInterface = await allProductsRes.json();

  const blogRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const allBlogs: BlogInterface[] = await blogRes.json();

  const bannerRes = await fetch("http://localhost:5001/banner_content");
  const banner: BlogInterface[] = await bannerRes.json();
  return {
    props: {
      allBlogs,
      allProducts,
      banner,
    },
  };
};

export default Home;
